server:
  port: ${PORT:${SERVER_PORT:0}}

#idRandom: ${random.value}

spring:
  application:
    name: api-movies
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}
management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
    app:
      name: api movies
      version: 1.0.0
      description: Películas

  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  data:
    mongodb:
      uri: mongodb://localhost:27017/moviesdb
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8085/realms/digitalHouse
        registration:
          keycloak:
            client-id: oldc-postman
            client-secret: T8kVwiojBQ8r7LShaUYXdgSFHhOvYCfZ
            scope: openid
            redirect-uri: http://localhost:8082
app:
  cors:
    allowed-origins: http://localhost:3000

#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/movie_dev
#    username: root
#    password: root
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true




